# read pair pattern
pat_r1: "{sample}_L001_R1_001.fastq.gz"
pat_r2: "{sample}_L001_R2_001.fastq.gz"

# flash overlap settings
max_overlap: 200
min_overlap: 20

# slit libraries QC
phred_threshold: 9
bad_run: 5
length_fraction: 0.7
read_indicator: "extendedFrags" 
